# example netlify.toml
[build]
  command = "CI= npm run build"
  functions = "netlify/functions"
  publish = "build"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
[[redirects]]
  from = "/ng-donation"
  to = "https://paystack.com/pay/togcfoundation"
  status = 200
  force = true

[[redirects]]
  from = "/international-donation"
  to = "https://www.paypal.com/donate/?hosted_button_id=CYLFYSXBZH6K2"
  status = 200
  force = true
